# Generated by Django 4.2.7 on 2023-11-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rua", models.CharField(max_length=255)),
                ("bairro", models.CharField(max_length=255)),
                ("numero", models.IntegerField()),
                ("cidade", models.CharField(max_length=255)),
                ("estado", models.CharField(max_length=255)),
                ("ponto_de_referencia", models.CharField(max_length=255)),
                ("cep", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Escolaridade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_da_escola", models.CharField(max_length=255)),
                (
                    "nivel_escolaridade",
                    models.CharField(
                        choices=[
                            ("EF completo", "Ensino Fundamental Completo"),
                            ("EF incompleto", "Ensino Fundamental Incompleto"),
                            ("EM completo", "Ensino Medio Completo"),
                            ("EM incompleto", "Ensino Medio Incompleto"),
                            ("Graduação", "Graduando"),
                            ("Pos-graduação", "Pos-graduação"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Irmaos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_completo", models.CharField(max_length=255)),
                ("data_de_nascimento", models.DateField()),
                ("pai", models.CharField(max_length=255)),
                ("mae", models.CharField(max_length=255)),
                ("endereco", models.ManyToManyField(related_name="endereco_irmao", to="arvore.endereco")),
                (
                    "escolaridade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escolaridade",
                        to="arvore.escolaridade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profissao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_da_profissao", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("salario_medio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("requisitos", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Trabalho",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "salario",
                    models.CharField(
                        choices=[
                            ("salario_1994", "70_Reais"),
                            ("salario_1995", "100_Reais"),
                            ("salario_1996", "112_Reais"),
                            ("salario_1997", "120_Reais"),
                            ("salario_1998", "130_Reais"),
                            ("salario_1999", "136_Reais"),
                            ("salario_2000", "151_reais"),
                            ("salario_2001", "180_reais"),
                            ("salario_2002", "200_reais"),
                            ("salario_2003", "240_reais"),
                            ("salario_2004", "260_reais"),
                            ("salario_2005", "300_reais"),
                            ("salario_2006", "350_reais"),
                            ("salario_2007", "380_reais"),
                            ("salario_2008", "415_reais"),
                            ("salario_2009", "465_reais"),
                            ("salario_2010", "510_reais"),
                            ("salario_2011", "545_reais"),
                            ("salario_2012", "622_reais"),
                            ("salario_2013", "678_reais"),
                            ("salario_2014", "724_reais"),
                            ("salario_2015", "788_reais"),
                            ("salario_2016", "880_reais"),
                            ("salario_2017", "937_reais"),
                            ("salario_2018", "954_reais"),
                            ("salario_2019", "998_reais"),
                            ("salario_2020", "1045_reais"),
                            ("salario_2021", "1100_reais"),
                            ("salario_2022", "1212_reais"),
                            ("salario_2023", "1320_reais"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("endereço", models.ManyToManyField(related_name="endereco", to="arvore.endereco")),
                ("profissao", models.ManyToManyField(related_name="sua_profissao", to="arvore.profissao")),
            ],
        ),
        migrations.CreateModel(
            name="Tios",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_completo", models.CharField(max_length=255)),
                ("data_de_nascimento", models.DateField()),
                ("cidade_natal", models.CharField(max_length=255)),
                (
                    "escolaridade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tios_escolaridade",
                        to="arvore.escolaridade",
                    ),
                ),
                ("primos", models.ManyToManyField(related_name="filhos", to="arvore.irmaos")),
            ],
        ),
        migrations.CreateModel(
            name="Primos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_completo", models.CharField(max_length=255)),
                ("data_de_nascimento", models.DateField()),
                ("cidade_natal", models.CharField(max_length=255)),
                ("pai", models.CharField(max_length=255)),
                ("mae", models.CharField(max_length=255)),
                (
                    "escolaridade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primos_escolaridade",
                        to="arvore.escolaridade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_completo", models.CharField(max_length=255)),
                ("data_de_nascimento", models.DateField()),
                ("cidade_natal", models.CharField(max_length=255)),
                (
                    "escolaridade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pais_escolaridade",
                        to="arvore.escolaridade",
                    ),
                ),
                ("filhos", models.ManyToManyField(related_name="pais", to="arvore.irmaos")),
            ],
        ),
        migrations.AddField(
            model_name="irmaos",
            name="trabalho",
            field=models.ManyToManyField(related_name="suas_profissoes", to="arvore.trabalho"),
        ),
    ]
