# Generated by Django 4.2.7 on 2023-11-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rua", models.CharField(max_length=255)),
                ("bairro", models.CharField(max_length=255)),
                ("numero", models.IntegerField()),
                ("cidade", models.CharField(max_length=255)),
                ("estado", models.CharField(max_length=255)),
                ("ponto_de_referencia", models.CharField(max_length=255)),
                ("cep", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Escolaridade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_da_escola", models.CharField(max_length=255)),
                (
                    "nivel_escolaridade",
                    models.CharField(
                        choices=[
                            ("EF completo", "Ensino Fundamental Completo"),
                            ("EF incompleto", "Ensino Fundamental Incompleto"),
                            ("EM completo", "Ensino Medio Completo"),
                            ("EM incompleto", "Ensino Medio Incompleto"),
                            ("Graduação", "Graduando"),
                            ("Pos-graduação", "Pos-graduação"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Irmaos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_completo", models.CharField(max_length=255)),
                ("data_de_nascimento", models.DateField()),
                ("pai", models.CharField(max_length=255)),
                ("mae", models.CharField(max_length=255)),
                ("endereco", models.ManyToManyField(related_name="endereco_irmao", to="arvore.endereco")),
                (
                    "escolaridade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="escolaridade",
                        to="arvore.escolaridade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profissao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_da_profissao", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("salario_medio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("requisitos", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Trabalho",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endereço", models.ManyToManyField(related_name="endereco", to="arvore.endereco")),
                ("profissao", models.ManyToManyField(related_name="sua_profissao", to="arvore.profissao")),
            ],
        ),
        migrations.CreateModel(
            name="Tios",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_completo", models.CharField(max_length=255)),
                ("data_de_nascimento", models.DateField()),
                ("cidade_natal", models.CharField(max_length=255)),
                (
                    "escolaridade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tios_escolaridade",
                        to="arvore.escolaridade",
                    ),
                ),
                ("primos", models.ManyToManyField(related_name="filhos", to="arvore.irmaos")),
            ],
        ),
        migrations.CreateModel(
            name="Primos",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_completo", models.CharField(max_length=255)),
                ("data_de_nascimento", models.DateField()),
                ("cidade_natal", models.CharField(max_length=255)),
                ("pai", models.CharField(max_length=255)),
                ("mae", models.CharField(max_length=255)),
                (
                    "escolaridade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="primos_escolaridade",
                        to="arvore.escolaridade",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pais",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_completo", models.CharField(max_length=255)),
                ("data_de_nascimento", models.DateField()),
                ("cidade_natal", models.CharField(max_length=255)),
                (
                    "escolaridade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pais_escolaridade",
                        to="arvore.escolaridade",
                    ),
                ),
                ("filhos", models.ManyToManyField(related_name="pais", to="arvore.irmaos")),
            ],
        ),
        migrations.AddField(
            model_name="irmaos",
            name="trabalho",
            field=models.ManyToManyField(related_name="suas_profissoes", to="arvore.trabalho"),
        ),
    ]
