# Generated by Django 4.2.7 on 2023-11-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trabalho",
            name="salario",
            field=models.CharField(
                choices=[
                    ("Salario Minimo 1994", "70 Reais"),
                    ("Salario Minimo 1995", "100 Reais"),
                    ("Salario Minimo 1996", "112 Reais"),
                    ("Salario Minimo 1997", "120 Reais"),
                    ("Salario Minimo 1998", "130 Reais"),
                    ("Salario Minimo 1999", "136 Reais"),
                    ("Salario Minimo 2000", "151 Reais"),
                    ("Salario Minimo 2001", "180 Reais"),
                    ("Salario Minimo 2002", "200 Reais"),
                    ("Salario Minimo 2003", "240 Reais"),
                    ("Salario Minimo 2004", "260 Reais"),
                    ("Salario Minimo 2005", "300 Reais"),
                    ("Salario Minimo 2006", "350 Reais"),
                    ("Salario Minimo 2007", "380 Reais"),
                    ("Salario Minimo 2008", "415 Reais"),
                    ("Salario Minimo 2009", "465 Reais"),
                    ("Salario Minimo 2010", "510 Reais"),
                    ("Salario Minimo 2011", "545 Reais"),
                    ("Salario Minimo 2012", "622 Reais"),
                    ("Salario Minimo 2013", "678 Reais"),
                    ("Salario Minimo 2014", "724 Reais"),
                    ("Salario Minimo 2015", "788 Reais"),
                    ("Salario Minimo 2016", "880 Reais"),
                    ("Salario Minimo 2017", "937 Reais"),
                    ("Salario Minimo 2018", "954 reais"),
                    ("Salario Minimo 2019", "998reais"),
                    ("Salario Minimo 2020", "1045 reais"),
                    ("Salario Minimo 2021", "1100 reais"),
                    ("Salario Minimo 2022", "1212 reais"),
                    ("Salario Minimo 2023", "1320 reais"),
                ],
                max_length=25,
                null=True,
            ),
        ),
    ]
