# Generated by Django 4.2.7 on 2023-11-24 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0002_alter_trabalho_salario"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trabalho",
            old_name="endereço",
            new_name="endereço_atual",
        ),
        migrations.RenameField(
            model_name="trabalho",
            old_name="profissao",
            new_name="profissao_atual",
        ),
        migrations.RenameField(
            model_name="trabalho",
            old_name="salario",
            new_name="salario_atual",
        ),
    ]
