# Generated by Django 4.2.7 on 2023-11-04 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0003_primos"),
    ]

    operations = [
        migrations.AddField(
            model_name="pais",
            name="filhos",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, related_name="pais", to="arvore.irmaos"
            ),
            preserve_default=False,
        ),
    ]
