# Generated by Django 4.2.7 on 2023-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0004_pais_filhos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pais",
            name="filhos",
        ),
        migrations.AddField(
            model_name="pais",
            name="filhos",
            field=models.ManyToManyField(related_name="pais", to="arvore.irmaos"),
        ),
    ]
