# Generated by Django 4.2.7 on 2023-11-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0004_remove_trabalho_endereço_atual_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mes",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "mes_do_ano",
                    models.CharField(
                        choices=[
                            ("Jn", "Janeiro"),
                            ("Fv", "Fevereiro"),
                            ("Mar", "Março"),
                            ("Abr", "Abril"),
                            ("Mai", "Maio"),
                            ("Jun", "Junho"),
                            ("Jul", "Julho"),
                            ("Ag", "Agosto"),
                            ("Set", "Setembro"),
                            ("Out", "Outubro"),
                            ("Nov", "Novembro"),
                            ("Dez", "Dezembro"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
