# Generated by Django 4.2.7 on 2023-11-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0005_mes"),
    ]

    operations = [
        migrations.AddField(
            model_name="antigotrabalho",
            name="data_de_admissão",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="antigotrabalho",
            name="data_de_demissão",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="trabalho",
            name="data_de_admissão",
            field=models.DateField(null=True),
        ),
    ]
