# Generated by Django 4.2.7 on 2023-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0005_remove_pais_filhos_pais_filhos"),
    ]

    operations = [
        migrations.AddField(
            model_name="tios",
            name="filhos",
            field=models.ManyToManyField(related_name="filhos", to="arvore.irmaos"),
        ),
    ]
