# Generated by Django 4.2.7 on 2023-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0006_tios_filhos"),
    ]

    operations = [
        migrations.AddField(
            model_name="irmaos",
            name="mae",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="irmaos",
            name="pai",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="primos",
            name="mae",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="primos",
            name="pai",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
