# Generated by Django 4.2.7 on 2023-11-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0008_endereco"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endereco",
            name="numero",
            field=models.IntegerField(),
        ),
    ]
