# Generated by Django 4.2.7 on 2023-11-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0009_alter_endereco_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="endereco",
            name="cep",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
