# Generated by Django 4.2.7 on 2023-11-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0010_endereco_cep"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escolaridade",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_da_escola", models.CharField(max_length=255)),
                (
                    "nivel_escolaridade",
                    models.CharField(
                        choices=[
                            ("EF completo", "Ensino Fundamental Completo"),
                            ("EF incompleto", "Ensino Fundamental Incompleto"),
                            ("EM completo", "Ensino Medio Completo"),
                            ("EM incompleto", "Ensino Medio Incompleto"),
                            ("Graduação", "Graduando"),
                            ("Pos-graduação", "Pos-graduação"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Trabalho",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("endereço", models.ManyToManyField(related_name="endereco", to="arvore.endereco")),
            ],
        ),
    ]
