# Generated by Django 4.2.7 on 2023-11-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0011_escolaridade_trabalho"),
    ]

    operations = [
        migrations.AddField(
            model_name="irmaos",
            name="escolaridade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="escolaridade",
                to="arvore.escolaridade",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pais",
            name="escolaridade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pais_escolaridade",
                to="arvore.escolaridade",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="primos",
            name="escolaridade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="primos_escolaridade",
                to="arvore.escolaridade",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tios",
            name="escolaridade",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tios_escolaridade",
                to="arvore.escolaridade",
            ),
            preserve_default=False,
        ),
    ]
