# Generated by Django 4.2.7 on 2023-11-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("arvore", "0012_irmaos_escolaridade_pais_escolaridade_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profissao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome_da_profissao", models.CharField(max_length=255)),
                ("descricao", models.TextField()),
                ("salario_medio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("requisitos", models.TextField()),
            ],
        ),
    ]
