from .pais import PaisSerializer
from .tios import TiosSerializer
from .irmaos import IrmaosSerializer
from .primos import PrimosSerializer
from .endereco import EnderecoSerializer
from .trabalho import TrabalhoSerializer
from .escolaridade import EscolaridadeSerializer
from .profissão import ProfissaoSerializer
from .mes import MesSerializer